version: '3.4'

services:
  vitiligotracker:
    image: vitiligotracker
    build:
      context: ./VitiligoTracker
      dockerfile: Dockerfile
    # ports:
    #   - "80:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/vitiligo.db
    volumes:
      - ./docker_data:/app/data
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - vitiligotracker
    restart: always
